# No.6201-6300  例文チャンク
DATA = {
"6201": {"ex": "【名】He sank into a mire of tax paperwork so deep that even the accountant sighed in sympathy.<br>【動】Don't let one small typo mire the entire report in an endless cycle of nitpicky revisions.", "tr": "【名】彼は税金の書類の泥沼に深くはまり込み、会計士でさえ同情のため息をついた。<br>【動】一つの小さな誤字が、報告書全体を果てしない揚げ足取りの修正の泥沼にはめないようにしなさい。"},
"6202": {"ex": "【形】The bereaved widow received nine casseroles in one day and quietly wondered what to do with them all.<br>【名】The support group welcomed the bereaved with warm tea and the comforting permission to simply sit in silence.", "tr": "【形】先立たれた未亡人は一日で九つのキャセロールを受け取り、それを全部どうすべきか静かに悩んだ。<br>【名】その支援グループは遺族を温かいお茶と、ただ黙って座っていいという慰めの許しで迎えた。"},
"6203": {"ex": "The novel so completely engrossed him that he missed his stop, his lunch, and an important phone call.", "tr": "その小説は彼をあまりに完全に夢中にさせたので、彼は降りる駅も昼食も大事な電話も逃した。"},
"6204": {"ex": "He placed undue importance on the office coffee, treating a weak brew as a personal betrayal.", "tr": "彼はオフィスのコーヒーに過度の重要性を置き、薄い一杯を個人的な裏切りのように扱った。"},
"6205": {"ex": "She read every zodiac sign in the paper, then chose to believe only the one predicting free snacks.", "tr": "彼女は新聞の星座占いを全部読み、それから無料のおやつを予言するものだけを信じることにした。"},
"6206": {"ex": "【名】The frog is an amphibian that seemed deeply unimpressed by the children's enthusiastic screaming.<br>【形】The military showed off its amphibian vehicle, which crawled from the lake looking oddly smug.", "tr": "【名】そのカエルは両生類で、子どもたちの熱狂的な叫び声に深く感心していない様子だった。<br>【形】軍はその水陸両用車を披露し、それは奇妙に得意げな様子で湖から這い上がってきた。"},
"6207": {"ex": "The oldest extant copy of the recipe revealed grandma's secret ingredient was simply twice the butter.", "tr": "そのレシピの現存する最古の写しは、祖母の秘密の材料が単にバター二倍だったことを明かした。"},
"6208": {"ex": "The heinous crime of finishing the shared office cake was solved by a single incriminating fork.", "tr": "共用のオフィスケーキを食べ切るという極悪な犯罪は、一本の決定的なフォークによって解決された。"},
"6209": {"ex": "He grinned sheepishly after realizing he had been enthusiastically waving at a total stranger.", "tr": "彼はまったくの他人に熱心に手を振っていたと気づき、恥ずかしそうににやりと笑った。"},
"6210": {"ex": "His sudden interest in materialism faded fast when he saw the price tag on the shiny new gadget.", "tr": "物質主義への彼の突然の興味は、ぴかぴかの新型ガジェットの値札を見た時、あっという間に冷めた。"},
"6211": {"ex": "The chef claimed his soup was a transcendent experience, though it tasted mostly of confident salt.", "tr": "そのシェフは自分のスープが超越的な体験だと主張したが、味は主に自信たっぷりの塩だった。"},
"6212": {"ex": "His foolproof plan to wake up early relied entirely on a single alarm he always slept through.", "tr": "早起きするという彼の絶対確実な計画は、いつも寝過ごす一つの目覚まし時計に完全に頼っていた。"},
"6213": {"ex": "【動】\"Who ate my sandwich?\" he rasped, having lost his voice yelling about the very same crime yesterday.<br>【名】The file has a rough rasp that took the sharp edge off the wood, and off the woodworker's patience.", "tr": "【動】「誰が俺のサンドイッチを食べた？」と彼は耳障りな声で言った。昨日まさに同じ犯罪について叫んで声を失っていたのだ。<br>【名】そのやすりは粗い研磨面を持ち、木材の鋭い角を、そして木工職人の忍耐をも削り落とした。"},
"6214": {"ex": "His untenable claim that he'd read the entire report collapsed the moment someone asked a single question.", "tr": "報告書を全部読んだという彼の維持できない主張は、誰かが一つ質問した瞬間に崩れ去った。"},
"6215": {"ex": "The city dweller romanticized the agrarian life until he met his first genuinely angry rooster.", "tr": "その都会人は、初めて本当に怒った雄鶏に出会うまで、農業の暮らしを美化していた。"},
"6216": {"ex": "He is chronically late, arriving to his own surprise party a full forty minutes after the surprise.", "tr": "彼は慢性的に遅刻し、自分のサプライズパーティーに、サプライズの丸四十分後に到着した。"},
"6217": {"ex": "Her tactful way of saying the haircut was 'bold' spared his feelings while telling him nothing useful.", "tr": "その髪型を「大胆」と言う彼女の機転の利いた言い方は、彼の気持ちを守りつつ、何ら有用なことは伝えなかった。"},
"6218": {"ex": "He overheard just a snippet of the conversation and spent all week inventing dramatic conclusions.", "tr": "彼は会話の断片だけを耳にし、一週間かけて劇的な結論を捏造して過ごした。"},
"6219": {"ex": "【形】His caustic review of the play was so brutal that the director framed it as a badge of honor.<br>【名】The plumber warned that pouring the caustic down the sink would only anger the ancient pipes further.", "tr": "【形】その劇への彼の辛辣な批評はあまりに容赦なく、監督はそれを名誉の勲章として額装した。<br>【名】配管工は、その腐食剤を流しに流しても、古い配管をさらに怒らせるだけだと警告した。"},
"6220": {"ex": "He made a derogatory comment about the office plant, which promptly wilted in silent, dramatic protest.", "tr": "彼はオフィスの観葉植物について軽蔑的な発言をし、それは即座に無言で劇的な抗議としてしおれた。"},
"6221": {"ex": "The treacherous patch of ice near the door claimed three coworkers and one very startled pizza delivery.", "tr": "ドア近くの危険な氷の一角は、三人の同僚と、非常に驚いたピザ配達を一件、犠牲にした。"},
"6222": {"ex": "He proudly showed his old passbook, whose balance was mostly a long, uninterrupted record of coffee.", "tr": "彼は古い預金通帳を誇らしげに見せたが、その残高は主にコーヒーの長く途切れない記録だった。"},
"6223": {"ex": "He agreed to help move, with the firm proviso that pizza and gratitude be supplied in abundance.", "tr": "彼は引っ越しの手伝いに同意したが、ピザと感謝をふんだんに提供するという厳格な条件付きだった。"},
"6224": {"ex": "His pallid face after the rollercoaster suggested he would be sticking to the merry-go-round from now on.", "tr": "ジェットコースターの後の彼の青白い顔は、彼が今後メリーゴーラウンドに専念することを物語っていた。"},
"6225": {"ex": "The vindictive cat waited three full days before knocking the guilty guest's phone into the fish tank.", "tr": "その執念深い猫は丸三日待ってから、罪深い客のスマホを水槽の中へ叩き落とした。"},
"6226": {"ex": "He smiled ruefully at the empty cookie jar, having forgotten that he himself had emptied it last night.", "tr": "彼は空のクッキー瓶に悔しそうに微笑んだ。昨夜それを空にしたのが自分自身だと忘れていたのだ。"},
"6227": {"ex": "【形】The one rogue printer in the office jammed only during urgent tasks, as if it enjoyed the drama.<br>【名】He played the lovable rogue in the movie, charming the audience while robbing every character blind.<br>【動】The single tomato plant rogued across the entire garden, strangling the polite, well-behaved herbs.", "tr": "【形】オフィスの一台の制御不能なプリンターは、まるで騒動を楽しむかのように緊急の仕事の時だけ紙詰まりを起こした。<br>【名】彼は映画で愛すべきならず者を演じ、あらゆる登場人物から根こそぎ盗みつつ観客を魅了した。<br>【動】その一本のトマトの苗は庭全体に暴走し、行儀のよい礼儀正しいハーブを絞め殺した。"},
"6228": {"ex": "The inquisitive toddler asked 'why' so many times that the tired parent began questioning reality itself.", "tr": "その好奇心旺盛な幼児が「なぜ」を何度も尋ねるので、疲れた親は現実そのものを疑い始めた。"},
"6229": {"ex": "The biology teacher explained how semen carries genetic information, while half the class stared at the ceiling.", "tr": "生物の教師は精液がどう遺伝情報を運ぶか説明したが、クラスの半分は天井を見つめていた。"},
"6230": {"ex": "After a fitful night of sleep interrupted by a snoring cat, he arrived at work resembling a tired ghost.", "tr": "いびきをかく猫に邪魔された断続的な夜の睡眠の後、彼は疲れた幽霊のような姿で出勤した。"},
"6231": {"ex": "His vacuous stare during the meeting revealed his mind was firmly somewhere on a distant, sunny beach.", "tr": "会議中の彼のうつろな視線は、彼の心が遠くの陽の当たるビーチのどこかにしっかりあることを露呈していた。"},
"6232": {"ex": "The resurgent interest in the old cafe puzzled the owner, who had changed absolutely nothing in years.", "tr": "その古いカフェへの復活した関心は、何年も何一つ変えていなかった店主を困惑させた。"},
"6233": {"ex": "【名】His nightly harangue about proper dishwashing technique had become the family's unofficial bedtime story.<br>【動】She began to harangue the committee about parking, and forty patient minutes later, still had not stopped.", "tr": "【名】適切な皿洗いの技術についての彼の毎晩の大演説は、家族の非公式な就寝前の物語になっていた。<br>【動】彼女は駐車について委員会に長々と説教を始め、辛抱強い四十分後もまだ止まらなかった。"},
"6234": {"ex": "He tried to truncate his long story for the impatient group, then somehow added two extra tangents.", "tr": "彼はせっかちな集団のために長話を切り詰めようとし、それからなぜか二つの余談を追加した。"},
"6235": {"ex": "A gentle zephyr drifted through the window and carried off the single most important paper on his desk.", "tr": "穏やかなそよ風が窓から漂い込み、彼の机の上でただ一つ最も重要な書類を運び去った。"},
"6236": {"ex": "The gallery chose to juxtapose a priceless sculpture with a half-eaten sandwich, and critics debated for weeks.", "tr": "そのギャラリーは値のつけられない彫刻を食べかけのサンドイッチと並置することを選び、評論家たちは何週間も議論した。"},
"6237": {"ex": "His crass joke at the elegant dinner landed with the grace of a brick dropped into a bowl of soup.", "tr": "上品なディナーでの彼の粗野な冗談は、スープの器に落とされたレンガのような優雅さで着地した。"},
"6238": {"ex": "The dogmatic food critic insisted there was exactly one correct way to boil an egg, and he alone knew it.", "tr": "その独断的な料理評論家は、卵を茹でる正しい方法はただ一つ存在し、彼だけがそれを知っていると言い張った。"},
"6239": {"ex": "The politician managed to obfuscate a simple yes-or-no question into a twenty-minute cloud of vague nouns.", "tr": "その政治家は単純なイエスかノーの質問を、二十分にわたるあいまいな名詞の雲へと巧みにぼかした。"},
"6240": {"ex": "His afternoon nap was sacrosanct, and even a ringing fire alarm was expected to show some patience.", "tr": "彼の午後の昼寝は極めて神聖で、鳴り響く火災報知器でさえ少しは辛抱を見せることが期待された。"},
"6241": {"ex": "The team's lackluster performance in the first half was only outdone by their lackluster excuses afterward.", "tr": "前半のそのチームの冴えないプレーは、その後の冴えない言い訳によってのみ上回られた。"},
"6242": {"ex": "The office iconoclast questioned the sacred tradition of Friday donuts, and was met with horrified silence.", "tr": "そのオフィスの因習打破主義者は、金曜のドーナツという神聖な伝統に疑問を呈し、恐怖の沈黙で迎えられた。"},
"6243": {"ex": "A true xenophile, he greeted every foreign tourist so enthusiastically they assumed he worked for the city.", "tr": "生粋の外国好きである彼は、あらゆる外国人観光客をあまりに熱烈に迎えたので、彼らは彼が市の職員だと思い込んだ。"},
"6244": {"ex": "The cat's nefarious plot to be fed twice involved pretending, with great skill, that no one had fed it once.", "tr": "二度餌をもらうというその猫の極悪な陰謀は、一度も餌をもらっていないふりを見事な腕前ですることを含んでいた。"},
"6245": {"ex": "His fallacious claim that dessert doesn't count if eaten standing up was, sadly, believed by no one.", "tr": "立って食べればデザートは勘定に入らないという彼の誤った主張は、悲しいことに誰にも信じられなかった。"},
"6246": {"ex": "The jubilant crowd celebrated the victory so loudly that the winning player couldn't hear his own interview.", "tr": "歓喜に満ちた群衆はあまりに大声で勝利を祝ったので、勝った選手は自分のインタビューが聞こえなかった。"},
"6247": {"ex": "The veracity of his fishing story dropped sharply each time he retold it and the fish grew another foot.", "tr": "彼の釣りの話の真実性は、語り直すたびに、魚がまた一フィート伸びるにつれて急落した。"},
"6248": {"ex": "【名】The piano virtuoso stunned the crowd, then admitted he still couldn't play chopsticks without wincing.<br>【形】She gave a virtuoso performance of parallel parking that drew unexpected applause from the sidewalk.", "tr": "【名】そのピアノの巨匠は聴衆を驚嘆させたが、いまだに顔をしかめずに「箸」を弾けないと認めた。<br>【形】彼女は名人芸的な縦列駐車を披露し、歩道から思いがけない拍手を浴びた。"},
"6249": {"ex": "The kids dawdled so long over choosing ice cream that it melted before a single decision was ever made.", "tr": "子どもたちはアイスクリーム選びにあまりにぐずぐずしたので、一つの決断が下される前にそれは溶けてしまった。"},
"6250": {"ex": "The yeasty smell of fresh bread drifted through the office, instantly dissolving everyone's productivity.", "tr": "焼きたてパンの酵母の香りがオフィスに漂い、全員の生産性を瞬時に溶かした。"},
"6251": {"ex": "The charming knave talked his way into the party, then quietly walked off with all the good appetizers.", "tr": "その魅力的な悪党は口先でパーティーに入り込み、それから旨い前菜を全部持ってこっそり立ち去った。"},
"6252": {"ex": "Her ebullient greeting at 7 a.m. was, for the non-morning people, both admirable and mildly threatening.", "tr": "午前七時の彼女のあふれんばかりの挨拶は、朝が苦手な人々にとって、称賛に値し、かつ軽く脅威的でもあった。"},
"6253": {"ex": "The pugnacious little terrier squared up to a Great Dane, utterly convinced it had a real fighting chance.", "tr": "その喧嘩早い小さなテリアは、勝算が本当にあると固く信じて、グレートデーンに立ち向かった。"},
"6254": {"ex": "The solemnity of the ceremony was briefly disturbed by a phone loudly playing a cheerful cartoon theme.", "tr": "その式典の厳粛さは、陽気なアニメのテーマ曲を大音量で流すスマホによって、しばし乱された。"},
"6255": {"ex": "A single cup of good coffee could invigorate him enough to face the truly horrifying stack of morning emails.", "tr": "一杯の良いコーヒーは、本当に恐ろしい朝のメールの山に立ち向かえるほど彼を元気づけることができた。"},
"6256": {"ex": "He threatened to litigate over the missing office stapler, drafting a formal letter of surprising length.", "tr": "彼は行方不明のオフィスのホチキスを巡って訴訟を起こすと脅し、驚くほどの長さの正式な手紙を起草した。"},
"6257": {"ex": "The querulous customer complained the free sample was too small, too warm, and disappointingly delicious.", "tr": "その不平の多い客は、無料試食が小さすぎ、温かすぎ、そして残念なほど美味しいと文句を言った。"},
"6258": {"ex": "His sanctimonious lecture on recycling was undercut by the plastic cup he was holding the entire time.", "tr": "リサイクルに関する彼の神聖ぶった説教は、その間ずっと握っていたプラスチックカップによって台無しにされた。"},
"6259": {"ex": "The rambunctious puppies turned a calm living room into a chaotic scene of scattered cushions and pure joy.", "tr": "その騒々しい子犬たちは、穏やかな居間を、散らばったクッションと純粋な喜びの混沌とした光景に変えた。"},
"6260": {"ex": "The unflappable pilot calmly announced the delay as though a passing volcano were merely a minor inconvenience.", "tr": "その動じないパイロットは、通りすがりの火山などほんの些細な不便であるかのように、落ち着いて遅延を告げた。"},
"6261": {"ex": "His verbose apology was so long that by the end, everyone had forgotten what he was even apologizing for.", "tr": "彼の多弁な謝罪はあまりに長く、終わる頃には何について謝っているのか全員が忘れていた。"},
"6262": {"ex": "Beleaguered by three back-to-back meetings, he began to view his lunch break as a distant, mythical legend.", "tr": "三つの立て続けの会議に苦しめられ、彼は昼休みを遠く神話的な伝説のように見なし始めた。"},
"6263": {"ex": "【名】Her only quibble with the perfect vacation was that it had, unforgivably, eventually ended.<br>【動】He loves to quibble over tiny details, once debating for an hour whether a hot dog qualifies as a sandwich.", "tr": "【名】完璧な休暇への彼女の唯一の不満は、それが許しがたくも、ついに終わってしまったことだった。<br>【動】彼は細かい点で屁理屈を言うのが大好きで、かつてホットドッグはサンドイッチかどうか一時間議論した。"},
"6264": {"ex": "【名】The picnickers claimed the grassy knoll, guarding the perfect shady spot from any and all latecomers.<br>【動】The distant church bells seemed to knoll gently across the valley, as though announcing nothing in particular.", "tr": "【名】ピクニックの一行は草の小山を占領し、完璧な日陰の場所をあらゆる遅刻者から守った。<br>【動】遠くの教会の鐘が、まるで特に何も告げていないかのように、谷を越えて穏やかに鳴り渡るようだった。"},
"6265": {"ex": "【名】The oddly shaped district was a textbook gerrymander, resembling a startled dragon more than a map.<br>【動】The party tried to gerrymander the seating chart so that all the loud relatives ended up at one distant table.", "tr": "【名】その奇妙な形の選挙区は教科書通りのゲリマンダーで、地図というより驚いた竜に似ていた。<br>【動】その一家は、うるさい親戚全員が一つの離れたテーブルに収まるよう、席次表を都合よくいじろうとした。"},
"6266": {"ex": "His iconoclastic decision to serve dessert first was condemned by traditionalists and adored by everyone under ten.", "tr": "デザートを先に出すという彼の因習打破的な決断は、伝統主義者に非難され、十歳未満の全員に敬愛された。"},
"6267": {"ex": "His passion for horticulture meant the balcony held forty pots and, tragically, room for exactly no people.", "tr": "園芸への彼の情熱のせいで、バルコニーには四十個の鉢と、悲劇的に、人の入る余地がまったくなかった。"},
"6268": {"ex": "The calumny that he snored in meetings spread through the office, though he insisted he was merely 'resting deeply.'", "tr": "彼が会議でいびきをかくという中傷はオフィスに広まったが、彼はただ「深く休んでいた」だけだと言い張った。"},
"6269": {"ex": "His bellicose stance on the correct way to load the dishwasher started a feud that lasted three long weekends.", "tr": "食洗機の正しい入れ方に対する彼の好戦的な姿勢は、三度の長い週末にわたる争いを引き起こした。"},
"6270": {"ex": "The loquacious taxi driver told his entire life story before the meter had even reached the first dollar.", "tr": "そのおしゃべりなタクシー運転手は、メーターが最初の一ドルに達する前に、自分の人生の全てを語った。"},
"6271": {"ex": "The neophyte confidently added salt instead of sugar, transforming the cake into a truly unforgettable experience.", "tr": "その初心者は自信満々に砂糖の代わりに塩を加え、そのケーキを実に忘れがたい体験へと変えた。"},
"6272": {"ex": "His quixotic quest to reply to every single email eventually cost him an entire, and quite lovely, weekend.", "tr": "全てのメールに一つ残らず返信するという彼の無謀な探求は、結局まるまる一つの、かなり素敵な週末を犠牲にした。"},
"6273": {"ex": "The puppy's winsome expression convinced everyone to forgive the shredded remains of a single, expensive slipper.", "tr": "その子犬の愛嬌のある表情は、ずたずたになった一足の高価なスリッパの残骸を全員に許させた。"},
"6274": {"ex": "The daily vexation of a squeaky chair finally drove him to oil it at 3 a.m. in a fit of quiet desperation.", "tr": "きしむ椅子の日々の苛立ちが、ついに彼を静かな絶望の発作の中、午前三時に油をさすまで追い込んだ。"},
"6275": {"ex": "He tried to feign surprise at the party, but he had accidentally read the group chat an hour earlier.", "tr": "彼はパーティーで驚いたふりをしようとしたが、一時間前にうっかりグループチャットを読んでしまっていた。"},
"6276": {"ex": "She continued to vacillate between two nearly identical shades of white paint for a truly heroic three weeks.", "tr": "彼女はほぼ同一の二つの白い塗料の色合いの間で、実に英雄的な三週間、ぐらつき続けた。"},
"6277": {"ex": "The hotel's opulence extended even to the towels, which were somehow too luxurious to actually use.", "tr": "そのホテルの豪華さはタオルにまで及び、それはなぜか実際に使うにはあまりに贅沢すぎた。"},
"6278": {"ex": "The torpid office cat moved only to relocate itself into whichever square of sunlight was currently warmest.", "tr": "その無気力なオフィスの猫は、その時最も暖かい陽だまりの一角へ移動するためだけに動いた。"},
"6279": {"ex": "Her zestful approach to the dull spreadsheet involved color-coding it into something resembling festive art.", "tr": "退屈な表計算への彼女の熱意ある取り組みは、それを祝祭的なアートのようなものに色分けすることを含んでいた。"},
"6280": {"ex": "His opinions were remarkably malleable, shifting instantly to match whoever had spoken to him most recently.", "tr": "彼の意見は驚くほど影響されやすく、最も直近に話しかけてきた者に合わせて即座に変化した。"},
"6281": {"ex": "His ardor for the new hobby lasted exactly until the moment it required him to leave the comfortable couch.", "tr": "新しい趣味への彼の情熱は、快適なソファを離れることを要求された瞬間まで、ちょうど続いた。"},
"6282": {"ex": "In an act of noble abnegation, he gave up the last slice of pizza, then quietly regretted it all evening.", "tr": "気高い自己犠牲の行為として、彼は最後のピザ一切れを譲り、それから晩じゅう静かに後悔した。"},
"6283": {"ex": "The sturdy yeoman worked his small farm alone, answering to no one but a very demanding flock of geese.", "tr": "その頑健な自営農民は小さな農場を一人で営み、非常に要求の多いガチョウの群れ以外の誰にも従わなかった。"},
"6284": {"ex": "The garrulous neighbor cornered him by the mailbox and, forty minutes later, still had not reached the point.", "tr": "そのおしゃべりな隣人は郵便受けのそばで彼を捕まえ、四十分後もまだ本題にたどり着いていなかった。"},
"6285": {"ex": "Buying a bigger freezer would obviate his weekly panic over where to store yet another bulk-purchased lasagna.", "tr": "より大きな冷凍庫を買えば、また一つ大量購入したラザニアをどこにしまうかという彼の毎週のパニックを未然に防げるだろう。"},
"6286": {"ex": "The con artist tried to bilk the old widow, not knowing she had spent forty years auditing tax fraud.", "tr": "その詐欺師は年老いた未亡人を騙し取ろうとしたが、彼女が四十年間脱税を監査してきたことを知らなかった。"},
"6287": {"ex": "His jocose remarks at the tense meeting either eased the mood or made everything considerably more awkward.", "tr": "緊迫した会議での彼のひょうきんな発言は、雰囲気を和らげたか、あるいは全てをかなり気まずくしたかのどちらかだった。"},
"6288": {"ex": "【副】\"The lost keys are somewhere over yonder,\" he said, gesturing vaguely at an entire, unhelpful field.<br>【形】The hikers admired the yonder peak for an hour before realizing they had a very long way still to go.<br>【名】He gazed into the great blue yonder, mostly to avoid making eye contact during the awkward silence.", "tr": "【副】「失くした鍵はあそこの向こうのどこかだ」と彼は、役に立たない野原全体をあいまいに指し示しながら言った。<br>【形】ハイカーたちは向こうの山頂を一時間眺め、それからまだ非常に長い道のりがあると気づいた。<br>【名】彼は大空の彼方を見つめたが、それは主に気まずい沈黙の間に目を合わせるのを避けるためだった。"},
"6289": {"ex": "The tiny town's annual cavalcade consisted of two decorated tractors, a marching band, and one confused goat.", "tr": "その小さな町の毎年の行列は、飾りつけられたトラクター二台、マーチングバンド、そして一匹の困惑したヤギで構成されていた。"},
"6290": {"ex": "His hubris in claiming he'd never lose at chess vanished the moment his eight-year-old niece said 'checkmate.'", "tr": "チェスで絶対に負けないという彼の傲慢さは、八歳の姪が「チェックメイト」と言った瞬間に消え去った。"},
"6291": {"ex": "The cat knocked the glass off the table with such calm malice that everyone suspected careful premeditation.", "tr": "その猫はあまりに冷静な悪意でグラスをテーブルから落としたので、全員が入念な計画性を疑った。"},
"6292": {"ex": "The ravenous hikers reached the summit and devoured their sandwiches faster than they could enjoy the view.", "tr": "飢えたハイカーたちは山頂に着き、景色を楽しむ暇もなくサンドイッチをむさぼり食った。"},
"6293": {"ex": "The astronomer showed the class a distant nebula, then had to explain it was not, in fact, a smudge on the lens.", "tr": "その天文学者はクラスに遠い星雲を見せ、それからそれが実はレンズの汚れではないと説明せねばならなかった。"},
"6294": {"ex": "The emaciated houseplant survived on nothing but forgotten promises and the occasional guilty splash of water.", "tr": "その痩せ細った観葉植物は、忘れられた約束と、時折の罪悪感からの水しぶきだけで生き延びていた。"},
"6295": {"ex": "His gauche attempt to compliment her cooking somehow turned into an accidental critique of her entire family.", "tr": "彼女の料理を褒めようという彼の無作法な試みは、なぜか彼女の家族全体への偶発的な批判に変わった。"},
"6296": {"ex": "The endless team-building exercises seemed designed to enervate the very morale they were meant to boost.", "tr": "その果てしないチームビルディングの演習は、高めるはずの士気そのものを奪うために作られたかのようだった。"},
"6297": {"ex": "The magician's final trick flabbergasted the audience, though it was mostly just a very confident use of a mirror.", "tr": "そのマジシャンの最後のトリックは観客をびっくり仰天させたが、それは主にただの非常に自信に満ちた鏡の使い方だった。"},
"6298": {"ex": "The movie's mawkish ending, in which even the villain cried over a puppy, left the whole theater groaning.", "tr": "悪役までもが子犬を見て泣くその映画の過度に感傷的な結末は、劇場全体をうめかせた。"},
"6299": {"ex": "One clumsy spill managed to sully both the pristine white carpet and his reputation as a careful houseguest.", "tr": "一度の不器用なこぼしが、真っ白なカーペットと、慎重な客としての彼の評判の両方を汚すことに成功した。"},
"6300": {"ex": "【名】A sudden guffaw from the back of the quiet library made every studying head snap up in unison.<br>【動】He tried to guffaw politely at the boss's weak joke, but it came out as a strangled, honking cough.", "tr": "【名】静かな図書館の奥からの突然の大笑いは、勉強中の全員の頭を一斉にはっと上げさせた。<br>【動】彼は上司のつまらない冗談に礼儀正しく大笑いしようとしたが、それは絞め殺されたような、ガチョウの鳴くような咳になって出た。"},
}
